version: '3.8'
services:
  postgres:
    image: groonga/pgroonga:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${S3_KEY_ID}
      - MINIO_ROOT_PASSWORD=${S3_KEY_SECRET}
    command: server --console-address :9001 /data

volumes:
    postgres_data:
    minio_data: